{% set version = "1.0.0" %}
{% set name = "etils" %}

# This is the recipe for etils
package:
   name: {{ name }}
   version: {{ version }}

source:
  git_url: https://github.com/google/etils/
  git_rev: v{{ version }}

build:
  number: 2
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: python -m pip install .[array-types, edc, epath, enp, epy, etqdm, etree, etree-dm, etree-tf ]

requirements:
  host:
     - pip {{ pip }}
     - python
     - git >=2.2
     - flit-core >=3.5,<4
 
  run:
   # conda build requirements
     - python
     - numpy {{ numpy }}
     - zipp
     - importlib_resources {{ importlib_resources }}
     - typing_extensions {{ typing_extensions }}
     - absl-py {{ absl_py }}
     - tqdm {{ tqdm }}
     - dm-tree {{ dm_tree }}
     - tensorflow-base {{ tensorflow }}

about:
  home: https://github.com/google/etils
  license: Apache License 2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: "Collection of eclectic utils for python."
  description: |
       etils (eclectic utils) is an open-source collection of utils for python.
       Each top-level submodule is a self-contained independent module
       (with its own BUILD rule), meant to be imported individually.
  dev_url: https://github.com/google/etils
  doc_url: https://github.com/google/etils

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
